on: [push]

jobs:
  compile_plugin:
    runs-on: ubuntu-latest
    name: Compile Plugin
    env:
      PLUGIN_TO_COMPILE: testcompile
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}

      - name: Download AMX Mod X Base Files
        run: |
          wget https://www.amxmodx.org/amxxdrop/1.9/amxmodx-latest-base-linux -O amxmodx-latest-base-linux
          wget https://www.amxmodx.org/amxxdrop/1.9/$(cat amxmodx-latest-base-linux) -O amxmodx-base-linux.tar.gz

      - name: Extract AMX Mod X Base Files
        run: tar -zxvf amxmodx-base-linux.tar.gz

      - name: Copy repo files into AMX Mod X directory
        run: cp -r scripting addons/amxmodx/

      - name: Compile with amxxpc
        run: cd addons/amxmodx/scripting/ && ./amxxpc ${{ env.PLUGIN_TO_COMPILE }}.sma -o${{ env.PLUGIN_TO_COMPILE }}.amxx

      - name: Release Plugin
        run: |
          gh release create ${{ env.TAG }} -n "${{ env.MESSAGE }}" -t "${{ env.NAME }}" ${{ env.FILES }} --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: "${{ steps.vars.outputs.short_ref }}_temp"
          MESSAGE: "latest build for this branch"
          NAME: "Latest for branch:  ${{ steps.vars.outputs.short_ref }}"
          FILES: addons/amxmodx/scripting/${{ env.PLUGIN_TO_COMPILE }}.amxx
