on: [push]

jobs:
  compile_plugin:
    runs-on: ubuntu-latest
    name: Compile Plugin
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download AMX Mod X Base Files
        run: |
          wget "https://www.amxmodx.org/latest.php?version=1.9&os=linux&package=base" -O amxmodx-base-linux.tar.gz
          tar -zxvf amxmodx-base-linux.tar.gz
      - name: Copy repo files into AMX Mod X directory
        run: cp -r scripting addons/amxmodx/
      - name: Compile with amxxpc
        run: cd addons/amxmodx/scripting/ && ./amxxpc testcompile.sma -omycompiledplugin.amxx
