on: [workflow_dispatch]

jobs:
  compile_and_release_plugin:
    runs-on: ubuntu-latest
    name: Compile and Release Plugin
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download AMX Mod X Base Files
        run: |
          wget https://www.amxmodx.org/amxxdrop/1.9/amxmodx-latest-base-linux -O amxmodx-latest-base-linux
          wget https://www.amxmodx.org/amxxdrop/1.9/$(cat amxmodx-latest-base-linux) -O amxmodx-base-linux.tar.gz
      - name: Extract AMX Mod X Base Files
        run: tar -zxvf amxmodx-base-linux.tar.gz
      - name: Copy repo files into AMX Mod X directory
        run: cp -r scripting addons/amxmodx/
      - name: Compile with amxxpc
        run: cd addons/amxmodx/scripting/ && ./amxxpc testcompile.sma -omycompiledplugin.amxx
      - name: Release Plugin
        run: |
          gh release create ${{ env.VERSION }} -n "${{ env.MESSAGE }}" -t "${{ env.NAME }}" ${{ env.FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: "tag-${{ env.GITHUB_RUN_ID }}"
          MESSAGE: "message for release ${{ env.GITHUB_RUN_ID }}"
          NAME: "release name ${{ env.GITHUB_RUN_ID }}"
          FILES: addons/amxmodx/scripting/testcompile.amxx
